import { Rule, Violation, Lead, DashboardMetrics, ChartDataPoint } from './types';
import { subMinutes, subHours, subDays, addDays } from 'date-fns';

export const RULES: Rule[] = [
  {
    id: 'rule-1',
    number: 1,
    name: 'Speed-to-Lead',
    description: 'No contact attempt made within the 3-minute SLA',
    severity: 'CRITICAL',
    status: 'ENFORCED',
    icon: '🚀',
    threshold: '≤ 3 minutes',
    violationCount: 7,
    enabled: true,
  },
  {
    id: 'rule-2',
    number: 2,
    name: 'Daily Follow-Up Gap',
    description: 'Minimum 2 outbound attempts per day not met',
    severity: 'WARNING',
    status: 'ACTIVE',
    icon: '⚠️',
    threshold: '2 attempts/day',
    violationCount: 12,
    enabled: true,
  },
  {
    id: 'rule-3',
    number: 3,
    name: 'Missed Inbound Call',
    description: 'Inbound caller without successful connection or callback',
    severity: 'CRITICAL',
    status: 'ENFORCED',
    icon: '📞',
    threshold: '< 15 minutes callback',
    violationCount: 4,
    enabled: true,
  },
  {
    id: 'rule-4',
    number: 4,
    name: 'Lead Abandonment Risk',
    description: 'No successful contact made within critical 24-48 hour window',
    severity: 'CRITICAL',
    status: 'ENFORCED',
    icon: '🛑',
    threshold: '24–48 hours',
    violationCount: 3,
    enabled: true,
  },
  {
    id: 'rule-5',
    number: 5,
    name: 'No Answer, No Follow-Up',
    description: 'No follow-up attempt 15 minutes after a no-answer outcome',
    severity: 'CRITICAL',
    status: 'ENFORCED',
    icon: '⏱️',
    threshold: '15 minutes',
    violationCount: 9,
    enabled: true,
  },
  {
    id: 'rule-6',
    number: 6,
    name: 'Reschedule Not Confirmed',
    description: 'Reschedule requested with no follow-up action logged',
    severity: 'WARNING',
    status: 'ACTIVE',
    icon: '🔁',
    threshold: '< 1 hour response',
    violationCount: 2,
    enabled: true,
  },
  {
    id: 'rule-7',
    number: 7,
    name: 'Cancelled Appointment Recovery',
    description: 'Appointment cancelled with no recovery attempt logged',
    severity: 'CRITICAL',
    status: 'ENFORCED',
    icon: '❌',
    threshold: 'Immediate',
    violationCount: 1,
    enabled: true,
  },
  {
    id: 'rule-8',
    number: 8,
    name: 'Unconfirmed Appointment',
    description: 'No confirmation attempt logged by cutoff (day before)',
    severity: 'WARNING',
    status: 'ACTIVE',
    icon: '🔔',
    threshold: 'Day before cutoff',
    violationCount: 5,
    enabled: true,
  },
  {
    id: 'rule-9',
    number: 9,
    name: 'No-Show Not Recovered',
    description: 'No recovery call made within 30 minutes of a no-show',
    severity: 'CRITICAL',
    status: 'ENFORCED',
    icon: '🚫',
    threshold: '30 minutes',
    violationCount: 2,
    enabled: true,
  },
  {
    id: 'rule-10',
    number: 10,
    name: 'Pipeline Stall',
    description: 'Leads inactive with no stage progression detected',
    severity: 'WARNING',
    status: 'ACTIVE',
    icon: '⏳',
    threshold: '48 hours no movement',
    violationCount: 8,
    enabled: true,
  },
  {
    id: 'rule-11',
    number: 11,
    name: 'Calendar Underutilized',
    description: 'Available appointment slots going unfilled',
    severity: 'WARNING',
    status: 'ACTIVE',
    icon: '📅',
    threshold: '< 70% capacity',
    violationCount: 0,
    enabled: true,
  },
  {
    id: 'rule-12',
    number: 12,
    name: 'Booking Conversion Drop',
    description: 'Conversion rate below expected performance baseline',
    severity: 'WARNING',
    status: 'ACTIVE',
    icon: '📉',
    threshold: '< baseline -20%',
    violationCount: 1,
    enabled: true,
  },
  {
    id: 'rule-13',
    number: 13,
    name: 'Lead Flow Interruption',
    description: 'Abnormal drop in lead intake detected',
    severity: 'CRITICAL',
    status: 'ENFORCED',
    icon: '🔥',
    threshold: '< 50% of daily average',
    violationCount: 0,
    enabled: true,
  },
  {
    id: 'rule-14',
    number: 14,
    name: 'No Bookings Window',
    description: 'No booking activity detected in defined time window',
    severity: 'WARNING',
    status: 'ACTIVE',
    icon: '❌',
    threshold: '4-hour window',
    violationCount: 0,
    enabled: true,
  },
];

const now = new Date();

export const VIOLATIONS: Violation[] = [
  {
    id: 'v-001',
    ruleId: 'rule-1',
    ruleName: 'Speed-to-Lead',
    ruleIcon: '🚀',
    severity: 'CRITICAL',
    status: 'ENFORCED',
    leadName: 'Marcus Rivera',
    leadPhone: '+1 (555) 234-8901',
    leadSource: 'Facebook Lead Ad',
    location: 'Austin, TX',
    detectedAt: subMinutes(now, 8),
    elapsed: '8 min ago',
    revenueImpact: 'Delayed contact significantly reduces booking probability.',
    enforcement: 'Immediate outreach required.',
    resolved: false,
    escalated: false,
  },
  {
    id: 'v-002',
    ruleId: 'rule-3',
    ruleName: 'Missed Inbound Call',
    ruleIcon: '📞',
    severity: 'CRITICAL',
    status: 'ENFORCED',
    leadName: 'Diane Thornton',
    leadPhone: '+1 (555) 876-3412',
    leadSource: 'Google Search',
    location: 'Austin, TX',
    detectedAt: subMinutes(now, 22),
    elapsed: '22 min ago',
    revenueImpact: 'Inbound leads represent highest booking intent.',
    enforcement: 'Immediate follow-up required.',
    resolved: false,
    escalated: true,
  },
  {
    id: 'v-003',
    ruleId: 'rule-5',
    ruleName: 'No Answer, No Follow-Up',
    ruleIcon: '⏱️',
    severity: 'CRITICAL',
    status: 'ENFORCED',
    leadName: 'Jason Whitfield',
    leadPhone: '+1 (555) 192-0043',
    leadSource: 'Referral',
    location: 'Austin, TX',
    detectedAt: subMinutes(now, 35),
    elapsed: '35 min ago',
    revenueImpact: 'Lead value decreases rapidly without continued outreach.',
    enforcement: 'Resume contact immediately.',
    resolved: false,
    escalated: false,
  },
  {
    id: 'v-004',
    ruleId: 'rule-4',
    ruleName: 'Lead Abandonment Risk',
    ruleIcon: '🛑',
    severity: 'CRITICAL',
    status: 'ENFORCED',
    leadName: 'Priya Nair',
    leadPhone: '+1 (555) 403-7821',
    leadSource: 'Instagram Ad',
    location: 'Austin, TX',
    detectedAt: subHours(now, 26),
    elapsed: '26 hrs ago',
    revenueImpact: 'High risk of revenue loss — critical window passed.',
    enforcement: 'Immediate call required.',
    resolved: false,
    escalated: false,
  },
  {
    id: 'v-005',
    ruleId: 'rule-9',
    ruleName: 'No-Show Not Recovered',
    ruleIcon: '🚫',
    severity: 'CRITICAL',
    status: 'ENFORCED',
    leadName: 'Carlos Mendes',
    leadPhone: '+1 (555) 608-5529',
    leadSource: 'Facebook Lead Ad',
    location: 'Austin, TX',
    detectedAt: subHours(now, 2),
    elapsed: '2 hrs ago',
    revenueImpact: 'This is recoverable revenue. Immediate action required.',
    enforcement: 'Recovery call required now.',
    resolved: false,
    escalated: false,
  },
  {
    id: 'v-006',
    ruleId: 'rule-2',
    ruleName: 'Daily Follow-Up Gap',
    ruleIcon: '⚠️',
    severity: 'WARNING',
    status: 'ACTIVE',
    leadName: 'Samantha Cole',
    leadPhone: '+1 (555) 312-6677',
    leadSource: 'TikTok Ad',
    location: 'Austin, TX',
    detectedAt: subHours(now, 4),
    elapsed: '4 hrs ago',
    revenueImpact: 'Lead value decreases without continued outreach.',
    enforcement: 'Resume follow-up sequence.',
    resolved: false,
    escalated: false,
  },
  {
    id: 'v-007',
    ruleId: 'rule-8',
    ruleName: 'Unconfirmed Appointment',
    ruleIcon: '🔔',
    severity: 'WARNING',
    status: 'ACTIVE',
    leadName: 'Trevor Banks',
    leadPhone: '+1 (555) 781-9903',
    leadSource: 'Google Search',
    location: 'Austin, TX',
    detectedAt: subHours(now, 6),
    elapsed: '6 hrs ago',
    revenueImpact: 'Unconfirmed appointments have higher no-show rates.',
    enforcement: 'Confirm appointment before cutoff.',
    resolved: false,
    escalated: false,
  },
  {
    id: 'v-008',
    ruleId: 'rule-10',
    ruleName: 'Pipeline Stall',
    ruleIcon: '⏳',
    severity: 'WARNING',
    status: 'ACTIVE',
    leadName: 'Michelle Park',
    leadPhone: '+1 (555) 094-2241',
    leadSource: 'Organic',
    location: 'Austin, TX',
    detectedAt: subHours(now, 52),
    elapsed: '2 days ago',
    revenueImpact: 'Pipeline velocity slowing. Deal at risk.',
    enforcement: 'Move forward or update lead status.',
    resolved: false,
    escalated: false,
  },
];

export const LEADS: Lead[] = [
  {
    id: 'l-001',
    name: 'Marcus Rivera',
    phone: '+1 (555) 234-8901',
    email: 'marcus.r@email.com',
    source: 'Facebook Lead Ad',
    stage: 'New',
    location: 'Austin, TX',
    createdAt: subMinutes(now, 8),
    lastContact: null,
    contactAttempts: 0,
    appointmentDate: null,
    value: 2400,
    tags: ['Hot Lead'],
    violations: ['v-001'],
    dayNumber: 1,
  },
  {
    id: 'l-002',
    name: 'Diane Thornton',
    phone: '+1 (555) 876-3412',
    email: 'diane.t@email.com',
    source: 'Google Search',
    stage: 'Contacted',
    location: 'Austin, TX',
    createdAt: subHours(now, 2),
    lastContact: subMinutes(now, 22),
    contactAttempts: 1,
    appointmentDate: null,
    value: 1800,
    tags: ['Inbound'],
    violations: ['v-002'],
    dayNumber: 1,
  },
  {
    id: 'l-003',
    name: 'Jason Whitfield',
    phone: '+1 (555) 192-0043',
    email: 'jason.w@email.com',
    source: 'Referral',
    stage: 'Contacted',
    location: 'Austin, TX',
    createdAt: subDays(now, 2),
    lastContact: subMinutes(now, 35),
    contactAttempts: 3,
    appointmentDate: null,
    value: 3200,
    tags: ['Referral'],
    violations: ['v-003'],
    dayNumber: 3,
  },
  {
    id: 'l-004',
    name: 'Priya Nair',
    phone: '+1 (555) 403-7821',
    email: 'priya.n@email.com',
    source: 'Instagram Ad',
    stage: 'New',
    location: 'Austin, TX',
    createdAt: subHours(now, 26),
    lastContact: null,
    contactAttempts: 0,
    appointmentDate: null,
    value: 2100,
    tags: ['At Risk'],
    violations: ['v-004'],
    dayNumber: 2,
  },
  {
    id: 'l-005',
    name: 'Carlos Mendes',
    phone: '+1 (555) 608-5529',
    email: 'carlos.m@email.com',
    source: 'Facebook Lead Ad',
    stage: 'No Show',
    location: 'Austin, TX',
    createdAt: subDays(now, 5),
    lastContact: subHours(now, 2),
    contactAttempts: 5,
    appointmentDate: subHours(now, 2),
    value: 4500,
    tags: ['No Show'],
    violations: ['v-005'],
    dayNumber: 5,
  },
  {
    id: 'l-006',
    name: 'Samantha Cole',
    phone: '+1 (555) 312-6677',
    email: 'samantha.c@email.com',
    source: 'TikTok Ad',
    stage: 'Qualified',
    location: 'Austin, TX',
    createdAt: subDays(now, 3),
    lastContact: subHours(now, 4),
    contactAttempts: 2,
    appointmentDate: null,
    value: 1900,
    tags: [],
    violations: ['v-006'],
    dayNumber: 3,
  },
  {
    id: 'l-007',
    name: 'Trevor Banks',
    phone: '+1 (555) 781-9903',
    email: 'trevor.b@email.com',
    source: 'Google Search',
    stage: 'Appointment Set',
    location: 'Austin, TX',
    createdAt: subDays(now, 4),
    lastContact: subHours(now, 6),
    contactAttempts: 4,
    appointmentDate: addDays(now, 1),
    value: 2800,
    tags: ['Appointment'],
    violations: ['v-007'],
    dayNumber: 4,
  },
  {
    id: 'l-008',
    name: 'Michelle Park',
    phone: '+1 (555) 094-2241',
    email: 'michelle.p@email.com',
    source: 'Organic',
    stage: 'Qualified',
    location: 'Austin, TX',
    createdAt: subDays(now, 7),
    lastContact: subHours(now, 52),
    contactAttempts: 6,
    appointmentDate: null,
    value: 3600,
    tags: ['Stalled'],
    violations: ['v-008'],
    dayNumber: 7,
  },
  {
    id: 'l-009',
    name: 'Kevin Adams',
    phone: '+1 (555) 551-8832',
    email: 'kevin.a@email.com',
    source: 'Facebook Lead Ad',
    stage: 'Appointment Confirmed',
    location: 'Austin, TX',
    createdAt: subDays(now, 6),
    lastContact: subHours(now, 8),
    contactAttempts: 7,
    appointmentDate: addDays(now, 2),
    value: 2200,
    tags: ['Confirmed'],
    violations: [],
    dayNumber: 6,
  },
  {
    id: 'l-010',
    name: 'Alicia Zhang',
    phone: '+1 (555) 229-4490',
    email: 'alicia.z@email.com',
    source: 'Google Search',
    stage: 'Won',
    location: 'Austin, TX',
    createdAt: subDays(now, 10),
    lastContact: subDays(now, 1),
    contactAttempts: 8,
    appointmentDate: subDays(now, 1),
    value: 4800,
    tags: ['Closed Won'],
    violations: [],
    dayNumber: 10,
  },
];

export const DASHBOARD_METRICS: DashboardMetrics = {
  totalLeads: 47,
  activeViolations: 8,
  criticalViolations: 5,
  leadsAtRisk: 6,
  bookingsToday: 3,
  bookingTarget: 8,
  conversionRate: 24.3,
  avgResponseTime: 7.2,
  revenueAtRisk: 22400,
  pipelineValue: 87600,
};

export const LEAD_FLOW_DATA: ChartDataPoint[] = [
  { name: 'Mon', leads: 12, violations: 3, value: 0 },
  { name: 'Tue', leads: 18, violations: 5, value: 0 },
  { name: 'Wed', leads: 9, violations: 2, value: 0 },
  { name: 'Thu', leads: 22, violations: 7, value: 0 },
  { name: 'Fri', leads: 15, violations: 4, value: 0 },
  { name: 'Sat', leads: 8, violations: 2, value: 0 },
  { name: 'Sun', leads: 5, violations: 1, value: 0 },
];

export const BOOKINGS_DATA: ChartDataPoint[] = [
  { name: 'Mon', bookings: 4, value: 8800 },
  { name: 'Tue', bookings: 6, value: 13200 },
  { name: 'Wed', bookings: 3, value: 6600 },
  { name: 'Thu', bookings: 7, value: 15400 },
  { name: 'Fri', bookings: 5, value: 11000 },
  { name: 'Sat', bookings: 2, value: 4400 },
  { name: 'Sun', bookings: 1, value: 2200 },
];

export const RESPONSE_TIME_DATA: ChartDataPoint[] = [
  { name: '12am', value: 2.1 },
  { name: '3am', value: 1.4 },
  { name: '6am', value: 3.2 },
  { name: '9am', value: 8.1 },
  { name: '12pm', value: 5.4 },
  { name: '3pm', value: 9.2 },
  { name: '6pm', value: 7.8 },
  { name: '9pm', value: 4.3 },
];
